//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_MantenedorOneClick.Models.Entities
{
    using System;
    
    public partial class BuscarProductoCodEntity
    {
        public decimal IDPRODUCTO { get; set; }
        public string CODPRODUCTO { get; set; }
        public string NOMBREPRODUCTO { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHATERMINO { get; set; }
        public string ESTADO { get; set; }
        public string ISAPRE { get; set; }
        public string USUARIOCREADOR { get; set; }
        public decimal VALOR { get; set; }
        public string BENEFICIARIO { get; set; }
    }
}
