//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_MantenedorOneClick.Models.Entities
{
    using System;
    
    public partial class BuscarProductoEntity
    {
        public decimal RUTAFILIADO { get; set; }
        public string NOMBREAFILIADO { get; set; }
        public string ISAPRE { get; set; }
        public string CODIGOPRODUCTO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> FOLIO { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public Nullable<decimal> CARGAS { get; set; }
        public Nullable<decimal> VISUALIZACIONES { get; set; }
    }
}
