//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_MantenedorOneClick.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MantenedorOneClickEntities : DbContext
    {
        public MantenedorOneClickEntities()
            : base("name=MantenedorOneClickEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PKG_MANTENEDOR_1CLICK_ACTIVARESTADO(string aFILRUT, Nullable<decimal> cODPRODUCTO, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var aFILRUTParameter = aFILRUT != null ?
                new ObjectParameter("AFILRUT", aFILRUT) :
                new ObjectParameter("AFILRUT", typeof(string));
    
            var cODPRODUCTOParameter = cODPRODUCTO.HasValue ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_MANTENEDOR_1CLICK_ACTIVARESTADO", aFILRUTParameter, cODPRODUCTOParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual int PKG_MANTENEDOR_1CLICK_TERMINARVIGENCIA(Nullable<decimal> cODPRODUCTO, string iSAPRE, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var cODPRODUCTOParameter = cODPRODUCTO.HasValue ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_MANTENEDOR_1CLICK_TERMINARVIGENCIA", cODPRODUCTOParameter, iSAPREParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual int PKG_MANTENEDOR_1CLICK_AGREGARPRODUCTO(Nullable<decimal> cODPRODUCTO, string nOMBRE, Nullable<System.DateTime> fECHAINICIO, string iSAPRE, string uSUARIOCREADOR, Nullable<decimal> vALOR, string bENEFICIARIO, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var cODPRODUCTOParameter = cODPRODUCTO.HasValue ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(decimal));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var fECHAINICIOParameter = fECHAINICIO.HasValue ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(System.DateTime));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            var uSUARIOCREADORParameter = uSUARIOCREADOR != null ?
                new ObjectParameter("USUARIOCREADOR", uSUARIOCREADOR) :
                new ObjectParameter("USUARIOCREADOR", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            var bENEFICIARIOParameter = bENEFICIARIO != null ?
                new ObjectParameter("BENEFICIARIO", bENEFICIARIO) :
                new ObjectParameter("BENEFICIARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_MANTENEDOR_1CLICK_AGREGARPRODUCTO", cODPRODUCTOParameter, nOMBREParameter, fECHAINICIOParameter, iSAPREParameter, uSUARIOCREADORParameter, vALORParameter, bENEFICIARIOParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual ObjectResult<BuscarProductoEntity> PKG_MANTENEDOR_1CLICK_BUSCARPRODUCTOS(string aFILRUT, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var aFILRUTParameter = aFILRUT != null ?
                new ObjectParameter("AFILRUT", aFILRUT) :
                new ObjectParameter("AFILRUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarProductoEntity>("PKG_MANTENEDOR_1CLICK_BUSCARPRODUCTOS", aFILRUTParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual ObjectResult<BuscarProductoCodEntity> PKG_MANTENEDOR_1CLICK_BUSCARPRODUCTOCOD(Nullable<decimal> cODPRODUCTO, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var cODPRODUCTOParameter = cODPRODUCTO.HasValue ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarProductoCodEntity>("PKG_MANTENEDOR_1CLICK_BUSCARPRODUCTOCOD", cODPRODUCTOParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual int PKG_MANTENEDOR_1CLICK_EDITARPRODUCTO(Nullable<decimal> cODPRODUCTO, string iSAPRE, string nOMBRE, string eSTADO, Nullable<decimal> vALOR, string bENEFICIARIO, Nullable<decimal> cONFIRMACION, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var cODPRODUCTOParameter = cODPRODUCTO.HasValue ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            var bENEFICIARIOParameter = bENEFICIARIO != null ?
                new ObjectParameter("BENEFICIARIO", bENEFICIARIO) :
                new ObjectParameter("BENEFICIARIO", typeof(string));
    
            var cONFIRMACIONParameter = cONFIRMACION.HasValue ?
                new ObjectParameter("CONFIRMACION", cONFIRMACION) :
                new ObjectParameter("CONFIRMACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_MANTENEDOR_1CLICK_EDITARPRODUCTO", cODPRODUCTOParameter, iSAPREParameter, nOMBREParameter, eSTADOParameter, vALORParameter, bENEFICIARIOParameter, cONFIRMACIONParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual ObjectResult<ListarProductoEntity> PKG_MANTENEDOR_1CLICK_LISTARPRODUCTOS(string iSAPRE, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarProductoEntity>("PKG_MANTENEDOR_1CLICK_LISTARPRODUCTOS", iSAPREParameter, oCOD_ERROR, oMSG_ERROR);
        }
    
        public virtual int PKG_MANTENEDOR_1CLICK_CAMBIARPRODUCTO(Nullable<decimal> cODPRODOLD, Nullable<decimal> cODPRODNEW, string iSAPRE, ObjectParameter oCOD_ERROR, ObjectParameter oMSG_ERROR)
        {
            var cODPRODOLDParameter = cODPRODOLD.HasValue ?
                new ObjectParameter("CODPRODOLD", cODPRODOLD) :
                new ObjectParameter("CODPRODOLD", typeof(decimal));
    
            var cODPRODNEWParameter = cODPRODNEW.HasValue ?
                new ObjectParameter("CODPRODNEW", cODPRODNEW) :
                new ObjectParameter("CODPRODNEW", typeof(decimal));
    
            var iSAPREParameter = iSAPRE != null ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_MANTENEDOR_1CLICK_CAMBIARPRODUCTO", cODPRODOLDParameter, cODPRODNEWParameter, iSAPREParameter, oCOD_ERROR, oMSG_ERROR);
        }
    }
}
